### ISSUE TITLE
Formatting of `.tf` files [Makefile] or pre-commit hook

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack-template#10]
_originally posted in [#306](https://github.com/fredrikhgrelland/vagrant-hashistack/issues/306) by @zhenik_

Use formating 
```
terraform fmt -recursive
```

**Comment by zhenik** [comment]
Might be useful to check [Git-hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) section `pre-commit`

**Comment by claesgill** [comment]
I have looked into `pre-commit` and it seems to be a nice way to do more testing, linting, check commit messages etc before pushing code. The implementation could be either big or small depending on what we want to include. Prehaps we should create a separate issue regarding this?

**Comment by claesgill** [comment]
New issue regarding `pre-commit` is #24
