### ISSUE TITLE
terraform_required_providers failures [LINTER]

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack-template#14]
## Logs
```
2020-09-16 10:08:54 [INFO  ]   File:[/tmp/lint/example/vagrant_box_example/nomad_acl.tf]
2020-09-16 10:08:55 [ERROR ]   Found errors in [tflint] linter!
2020-09-16 10:08:55 [ERROR ]   [1 issue(s) found:

Warning: Missing version constraint for provider "vault" in "required_providers" (terraform_required_providers)

  on /tmp/lint/example/vagrant_box_example/nomad_acl.tf line 1:
   1: data "vault_generic_secret" "nomad_secret_id" {

Reference: https://github.com/terraform-linters/tflint/blob/v0.20.1/docs/rules/terraform_required_providers.md]
```

**Disabling concrete rule [is not supported yet](https://github.com/github/super-linter/blob/master/docs/disabling-linters.md#tflint-disable-entire-file)**

## Solution 1
Set rule to `false`, for now. 
https://github.com/fredrikhgrelland/vagrant-hashistack-template/blob/master/.github/linters/.tflint.hcl#L25-L27 

We should think about how to follow `DRY` principle and have only one file with the required providers block
```
terraform {
  required_providers {
    nomad = {
      source  = "hashicorp/nomad"
      version = "~> 1.4.9"
    }
    template = {
      source  = "hashicorp/template"
      version = "~> 2.1.2"
    }
  }
  required_version = ">= 0.13"
}
```

**Comment by claesgill** [comment]
If this is this still an issue, how can I recreate it?

**Comment by zhenik** [comment]
Uncomment these lines https://github.com/fredrikhgrelland/vagrant-hashistack-template/blob/master/.github/linters/.tflint.hcl#L25-L27
