### ISSUE TITLE
Decouple template tasks and box tasks

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack-template#19]
https://github.com/fredrikhgrelland/vagrant-hashistack/issues/336

**Comment by claesgill** [comment]
@pdmthorsrud 
Is this still an issue? If so, please elaborate and add any suggestions you may have.

**Comment by pdmthorsrud** [comment]
This was in broad terms fixed by https://github.com/fredrikhgrelland/vagrant-hashistack-template/commit/252ea22fe68790f25638e8c439091f7461f37981
