### ISSUE TITLE
Add pre-commit helper command

### ISSUE THREAD

**Issue by claesgill** [fredrikhgrelland/vagrant-hashistack-template#24]
Add `make pre-commit` helper command in the `Makefile` that will check for flaws/error/linter etc in your code so that when you create a PR it shouldn't fail. 

Definition of done:
- Add `make pre-commit` that does:
    - Linting
    - Formatting

**Comment by pdmthorsrud** [comment]
It needs to check linter and format tf-files IMO. Nothing more at this point
