### ISSUE TITLE
Sync template with modules

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack-template#32]
## Problem
Once a user creates a new repository from the template, that new repository has no common git-history with the original template. 

## How to resolve
Originally posted [here](https://github.com/fredrikhgrelland/terraform-nomad-minio/pull/9#issue-476234355)

Basically  **git merge**. 

### Applied strategy - the first time only
1. Add remote upstream to template origin `git remote add template [URL of the template repo]`
2. Fetch all `git fetch --all`
3. Checkout **template** master branch. Its important to have it locally. 
4. Checkout new branch from **origin** master
5. Run git merge with the flag `--allow-unrelated-histories` 
6. fix conflicts
7. commit
8. PR against current master

[ref stackoverflow](https://stackoverflow.com/a/56577320)

**Comment by pdmthorsrud** [comment]
Do I understand correctly that you can do a normal rebase after the histories have been merged?

**Comment by zhenik** [comment]
> Do I understand correctly that you can do a normal rebase after the histories have been merged?

Not sure. We need to research that

_There is still question -> do we need do the merge only once then we can use rebase due to that histories are related (after the first merge)_
