### ISSUE TITLE
Add healthcheck to the countdash example

### ISSUE THREAD

**Issue by Neha-Sinha2305** [fredrikhgrelland/vagrant-hashistack-template#56]
Adding healthcheck ansible task to the countdash example will serve two purpose:

1. Uncover regressions much before the changed code is rolled out to downstream modules : [fredrikhgrelland/vagrant-hashistack#344](https://github.com/fredrikhgrelland/vagrant-hashistack/issues/344)

2. Provide **users of the template** with an working example of test that could be added for the modules that they develop :
[healthcheck-terraform-nomad-hive](https://github.com/fredrikhgrelland/terraform-nomad-hive/blob/master/dev/ansible/03_healthcheck_test.yml)

**Comment by Neha-Sinha2305** [comment]
@zhenik : What are your thoughts?
(I can assign it to myself if this sounds ok to you.)

**Comment by zhenik** [comment]
> @zhenik : What are your thoughts?
> (I can assign it to myself if this sounds ok to you.)

Sure, if you have time
