### ISSUE TITLE
Make dev running all ansible tests

### ISSUE THREAD

**Issue by claesgill** [fredrikhgrelland/vagrant-hashistack-template#57]
Issue with `make dev` that runs all ansible-playbooks with `tag=test` although `ANSIBLE_ARGS='--skip-tags "test"` is set.

**Comment by pdmthorsrud** [comment]
You need to send the ansible args to ansible
https://github.com/fredrikhgrelland/terraform-nomad-presto/blob/1d4de77db8d7dddf014c7bd6e0f6bfd51c0d6fc9/Vagrantfile.default#L10-L13
