### ISSUE TITLE
Update box version

### ISSUE THREAD

**Issue by claesgill** [fredrikhgrelland/vagrant-hashistack-template#66]
## Feature description
Update box version to vagrant-hashistack latest

## Why is it needed?
Because new template structure supports latest vagrant-hashistack version

## Suggestion(s)/solution(s) [Optional]
Update `Vagrantfile.default`

## Definition of done
Box version >= 0.6.x

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

**Comment by pdmthorsrud** [comment]
Add a check for this when releases happen?
