### ISSUE TITLE
Fix ansible playbook documentation

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/vagrant-hashistack-template#72]
## Feature description
Add proper documentation to the ansible playbooks. https://github.com/fredrikhgrelland/vagrant-hashistack-template/tree/master/dev/vagrant/bootstrap

## Why is it needed?
The doc that is there now is not understandable. Does not describe what directory structure is needed to add pre and post bootstrap books.

## Definition of done
A description of how to add books

## Checklist (after created issue)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

**Comment by zhenik** [comment]
Does [PR #70](https://github.com/fredrikhgrelland/vagrant-hashistack-template/pull/70) fix this issue?

**Comment by pdmthorsrud** [comment]
Seems like it does, yeah. I will have to review that PR after the meeting in half an hour!
