### ISSUE TITLE
Update make:clean command [Makefile]

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack-template#8]
_originally posted [#306](https://github.com/fredrikhgrelland/vagrant-hashistack/issues/306) by @zhenik_

```
make clean
```
does 
- destroy vagrant box
- remove all temporary folders and files

**Comment by dangernil** [comment]
Do you have any more info in this issue @zhenik ? We do have a make clean that destroy box and remove all tmp files

**Comment by zhenik** [comment]
> Do you have any more info in this issue @zhenik ? We do have a make clean that destroy box and remove all tmp files

You understand me right.  Example of temp folders

<img width="386" alt="Screenshot 2020-09-17 at 13 41 12" src="https://user-images.githubusercontent.com/15572799/93465782-89230c80-f8eb-11ea-94b6-8a18cf2e0446.png">
