### ISSUE TITLE
Simplify template and focus less on paedagogy and more on usability

### ISSUE THREAD

**Issue by oschistad** [fredrikhgrelland/vagrant-hashistack-template#83]
## What is the issue?
When cloning this template I am going to be in the context of developing a new service based on the vagrant-hashistack + terraform + nomad ecosystem. RIght now, the first thing I have to do is to get rid of the countdash and template_example stuff and wire up my own, empty example, before I can start actively developing.

## Suggestion(s)/solution(s) [Optional]

- Remove template_example folder.
- Set up example folder as an empty nomad template with a subfolder for vagrant testing which sets up nomad provider
- Wire up vagrant to run the example terraform code at startup

Desired end result is that it works out of box, with a default terraform module posting an empty nomad job on startup.
This eliminates all cleanup required just to start developing a new module

## Checklist (after created issue)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

**Comment by zhenik** [comment]
related #67

**Comment by pdmthorsrud** [comment]
Possible solve this with a target in our makefile? E.g. `make init` removes unnecessary files, adds files, etc.

**Comment by claesgill** [comment]
Planned TODOs:
- Rename folder root conf 👉 nomad
- Merge Vagrantfile with Vagrantfile.default
- New target `make init` that removes unnecessary files and folders such as:
    - GETTING_STARTED
    - template_example
    - README.md
    - example/vagrantbox

Do you have other suggestions? @oschistad @fredrikhgrelland
