### ISSUE TITLE
Template for modules missing /con/nomad directory

### ISSUE THREAD

**Issue by karimacherradi** [fredrikhgrelland/vagrant-hashistack-template#89]
## Current behaviour
When running the template to create a new terraform-modul, the directory structure is missing the /conf/nomad directory

## Expected behaviour
/conf/nomad directory should come up with the other necessary directories where running the template for new terraform-modul.
I expect all the directories as show here:
https://github.com/fredrikhgrelland/vagrant-hashistack-template/blob/master/GETTING_STARTED/getting_started_modules.md#directory-structure

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

**Comment by claesgill** [comment]
The `conf/nomad` folder is renamed to `nomad`. We do not use any other that nomad jobs in `conf` thus the rename.

The only thing to keep in mind is when specifying the nomad file in `main.tf`, the path should not include `conf`. See example: https://github.com/fredrikhgrelland/vagrant-hashistack-template/blob/master/template_example/main.tf#L2

Closing issue.
