### ISSUE TITLE
Check for necessary binaries [Makefile]

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack-template#9]
_originally posted [#306](https://github.com/fredrikhgrelland/vagrant-hashistack/issues/306) by @zhenik_

Some of the commands in `Makefile` require binaries available on `PATH`, such as
- `consul` (to build a local proxy to the container)
- ...

Todo:
- [x] add check for binaries availability

[Example](https://github.com/fredrikhgrelland/terraform-nomad-redash/blob/e8dec7d3c4f1f5f2330a4def49cbaaf04a0bc5a8/Makefile#L12)

**Comment by Neha-Sinha2305** [comment]
https://github.com/fredrikhgrelland/terraform-nomad-redash/blob/e8dec7d3c4f1f5f2330a4def49cbaaf04a0bc5a8/Makefile#L12
