### ISSUE TITLE
Vagrant box not booting

### ISSUE THREAD

**Issue by gustavnordgren** [fredrikhgrelland/vagrant-hashistack-template#90]
## Current behaviour
Vagrant box not booting with vagrant up or make up:

k82391@u1804i-0371:~/vagrant/vagrant-hashistack-template$ make up
==> default: Checking for updates to 'fredrikhgrelland/hashistack'
    default: Latest installed version: 0.9.0
    default: Version constraints: >= 0.9, < 1.0
    default: Provider: virtualbox
==> default: Box 'fredrikhgrelland/hashistack' (v0.9.0) is running the latest version.
SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt CUSTOM_CA= vagrant up --provision
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Preparing master VM for linked clones...
    default: This is a one time operation. Once the master VM is prepared,
    default: it will be used as a base for linked clones, making the creation
    default: of new VMs take milliseconds on a modern system.
==> default: Importing base box 'fredrikhgrelland/hashistack'...
==> default: Cloning VM...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'fredrikhgrelland/hashistack' version '0.9.0' is up to date...
==> default: Setting the name of the VM: vagrant-hashistack-template_default_1611920696624_71207
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 8500 (guest) => 8500 (host) (adapter 1)
    default: 4646 (guest) => 4646 (host) (adapter 1)
    default: 8200 (guest) => 8200 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...

retrying until timeout...
the same thing happens with box version set to v0.7.1

## Expected behaviour
Vagrant box booting

## How to reproduce?
make up

## Checklist (after created issue)
- [ ] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

**Comment by pdmthorsrud** [comment]
https://github.com/fredrikhgrelland/terraform-nomad-presto/issues/54#issuecomment-717199130

Could you post the output of `sudo vagrant global-status`?

**Comment by fredrikhgrelland** [comment]
Closing due to no response

**Comment by pdmthorsrud** [comment]
I believe this might have actually been solved by Gustav. Any input on what fixed it (or didn't), @gustavnordgren?

**Comment by gustavnordgren** [comment]
@pdmthorsrud I am not certain what caused the specific issue, however it was resolved after several reboots of Ubuntu environment.

**Comment by pdmthorsrud** [comment]
> @pdmthorsrud I am not certain what caused the specific issue, however it was resolved after several reboots of Ubuntu environment.

Got it, thanks for the input :+1:
