### ISSUE TITLE
`make template_init` failing on iterm2

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/vagrant-hashistack-template#97]
## Current behaviour

```sh
> make template_init
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```

## Expected behaviour
Init template

## How to reproduce?
Open project in iTerm2, and run
```sh
make template_init
```

## Checklist (after created issue)
- [X] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

**Comment by fredrikhgrelland** [comment]
This error has nothing to do with the template nor the vagrant box.
If this surfaces for anybody - run `xcode-select --install`
